# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

# Permalinks
permalink: pretty

# Server
source: site
destination: ./_gh_pages
host: 0.0.0.0
port: 9001
baseurl: ''
url: ''
encoding: UTF-8
exclude:
- assets/scss/

plugins:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-toc

redirect_from:
  json: false

# Social
title: The Title
description: A Description
twitter: ...
authors: ...
social_image_path: /assets/brand/bootstrap-social.png
social_logo_path: /assets/brand/bootstrap-social-logo.png

# Custom variables
current_version: 4.5.3
current_ruby_version: 4.5.3
github_org: ...
repo: ...
slack: ...
opencollective: ...
blog: https://blog.getbootstrap.com
expo: https://expo.getbootstrap.com
themes: https://themes.getbootstrap.com
icons: https://icons.getbootstrap.com

download:
  source: https://github.com/twbs/bootstrap/archive/v4.5.3.zip
  dist: https://github.com/twbs/bootstrap/releases/download/v4.5.3/bootstrap-4.5.3-dist.zip
  dist_examples: https://github.com/twbs/bootstrap/releases/download/v4.5.3/bootstrap-4.5.3-examples.zip

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css: https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/css/bootstrap.min.css
  css_hash: sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2
  js: https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.min.js
  js_hash: sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s
  js_bundle: https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.bundle.min.js
  js_bundle_hash: sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx
  jquery: https://code.jquery.com/jquery-3.5.1.slim.min.js
  jquery_hash: sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj
  popper: https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js
  popper_hash: sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN

toc:
  min_level: 2
  max_level: 4
  no_toc_section_class:
  - bd-callout
  - bd-example
