project-site:
  version: 0.0.2
  builder: bootstrap45
  publish: gh-pages

title: Project Site
description: A static site generator for projects

code:
  repo: https://github.com/ingydotnet/project-site
  branch: www

page:
  layout: default
  toc: true

theme:
  color: green
  logo:
    type: template
    letters: PS

social:
  github: https://github.com/ingydotnet/project-site
  twitter: https://twitter.com/ProjectSiteNews

navbar:
  left:
  - type: logo

  right:
  - type: github
  - type: twitter

sidebar:
- title: Home

copyright:
  who: Ingy d√∂t Net
  when: 2020
  license: MIT
